### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by zgtibu** [tahaluindo/Gmail-BOTV2#14]
UnboundLocalError: local variable 'driver' referenced before assignment

**Comment by tahaluindo** [comment]
SS

**Comment by zgtibu** [comment]
![image](https://user-images.githubusercontent.com/69414194/202918675-d1c2eade-f265-4e86-9819-48ad6f59cf88.png)

**Comment by zgtibu** [comment]
![image](https://user-images.githubusercontent.com/69414194/202918712-20b1e774-c717-4f80-8d56-070ed3ce481b.png)

**Comment by zgtibu** [comment]
![image](https://user-images.githubusercontent.com/69414194/202918728-a891cdc1-6cb6-4625-bb94-a5563bfe13c8.png)

**Comment by zgtibu** [comment]
![image](https://user-images.githubusercontent.com/69414194/202918741-12d5639e-0d09-4bc4-bedf-88629108f339.png)

**Comment by tahaluindo** [comment]
`git pull` and `python beta.py`

**Comment by zgtibu** [comment]
Traceback (most recent call last):
  File "C:\Users\91989\Downloads\Gmail-BOTV2-main\Gmail-BOTV2-main\beta.py", line 2, in <module>
    from src.igniter import Igniter
  File "C:\Users\91989\Downloads\Gmail-BOTV2-main\Gmail-BOTV2-main\src\igniter.py", line 1
    {full_name[0]}{full_name[1]}{random.randint(1,999)}", get_random_string(12), random.choice(ua), self.config["api_key"], self.CLI, thread_id, random.choice(self.proxies) if self.proxies else None).create_account() if data: self.remaining -= data else: pass for thread_id in range(0, self.thread): self.CLI.set(index=thread_id, status='Completed.') sys.exit() def thread_base(self): threads = [] for thread_id in range(0, self.thread): t = threading.Thread(target=self.thread_function, daemon=True, args=(thread_id,)) threads.append(t) t.start() for t in threads: t.join() def main(self): self.thread_base()
                                 ^^^^
SyntaxError: invalid syntax

**Comment by maillenniums** [comment]
me too

**Comment by tahaluindo** [comment]
python barubang.py
